version: 2.1
orbs:
  codecov: codecov/codecov@3

jobs:
  test-with-coverage:
    docker:
      - image: cimg/python:3.10
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt
      - run:
          name: Set up Code Climate
          command: |
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
            ./cc-test-reporter before-build
      - run:
          name: Run tests
          command: |
            pytest -sv --cov autobean --cov-report xml
      - run:
          name: Upload coverage to Code Climate
          command: ./cc-test-reporter after-build --exit-code $?
      - codecov/upload
      - run:
          name: Run type checks
          command: mypy autobean

workflows:
  test-on-push:
    jobs:
      - test-with-coverage:
          filters:
            branches:
              only: master
